### ISSUE TITLE
Improve reporting and error/warning messages

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#16]
- [x] Provide more detailled REP/REPIN report: How many repins found in each group, not just the summary
- [x] Provide more details in cases where rarefan reports "There has been a problem, please inspect log and output files."

**Comment by CFGrote** [comment]
Addressed in commit bae5d98. Now the results page gives a detailed account of the status (setup/queued/running/failed/complete/finished) and return code of each stage. If a return code is not 0, the error log is printed out.

attached screenshots are from a local test run, so this run is not available on rarefan.evolbio.mpg.de

![image](https://user-images.githubusercontent.com/15476807/194502486-27c7a206-0550-440f-8cfd-0c83ceaa548d.png)
![image](https://user-images.githubusercontent.com/15476807/194502591-187025ce-5486-4608-b777-c53adbf81ff2.png)
![image](https://user-images.githubusercontent.com/15476807/194502650-875e1834-bfa9-45f1-ba72-ce303e876a36.png)

**Comment by CFGrote** [comment]
@fredeBio , please comment

**Comment by fredeBio** [comment]
Hey Carsten, that looks great!!! Not sure about the importance of the middle picture. I mean it is just MUSCLE parameters right? Also for the last table I would probably have a matrix instead that shows REPs and REPINs for each Group. What do you think?

**Comment by CFGrote** [comment]
what you call "middle picture" is the log from phyml. logs are only printed out for stages that fail to complete. if everything is fine, no log. here it fails because there are less than 3 sequences to compare.

**Comment by CFGrote** [comment]
> Hey Carsten, that looks great!!! Not sure about the importance of the middle picture. I mean it is just MUSCLE parameters right? Also for the last table I would probably have a matrix instead that shows REPs and REPINs for each Group. What do you think?

I guess this is related to #22?

**Comment by fredeBio** [comment]
Yeah, do you think we need to print out the whole log if we already know what caused the error?

**Comment by CFGrote** [comment]
> Yeah, do you think we need to print out the whole log if we already know what caused the error?

yes, i'd like to include as many information as possible that may be important to track down the root cause for the failure.

**Comment by fredeBio** [comment]
Well, but at this point we do know the cause. So there is no point to add all that information. If we do not know the cause, then I would agree that we it is worth providing more information.

**Comment by fredeBio** [comment]
Ah right. Erm I think I understand. I guess we can leave it like this.
