### ISSUE TITLE
Discuss why presAbs_?.txt and maxREPIN_?.txt are sometimes empty

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#21]
The webserver user manual must provide explanation why the above mentioned files are empty in some cases, although RAYTs and REPINs have been found. See #18.

**Comment by CFGrote** [comment]
@fredeBio, Is this done?

**Comment by fredeBio** [comment]
Well, I think the discussion is a bit wrong. presAbs is never empty when REPINs have been found. It can be empty if no REPINs were found. It also sometimes contains only a subset of strains where REPINs have been identified not showing strains where REPINs were not found. 

Where is the webserver user manual?

**Comment by fredeBio** [comment]
[manual.zip](https://github.com/mpievolbio-scicomp/rarefan/files/9978081/manual.zip)
here is the updated manual

**Comment by CFGrote** [comment]
updated manual in 9b6e2e6
