### ISSUE TITLE
REP/REPIN table

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#22]
Ich habe gerade RAREFAN laufen lassen. Können wir vielleicht die REP/REPIN Ausgabe als Tabelle machen? Für jeden Strain eine Spalte und REP/REPINs differenziert ausgeben: #REPINs(#REPs)

**Comment by CFGrote** [comment]
Do you want to report #REPs always or only when "Analyze REPINs" is switched off? And do you want to report #REP(IN)s for each group or only the sum? would be helpful to see an example of the table you have in mind.

**Comment by fredeBio** [comment]
yes, I think we can report REPs always. we can report REPINs for each group. We can talk about it again if you like

**Comment by CFGrote** [comment]
## "Analyze Repins" unticked:
![image](https://user-images.githubusercontent.com/15476807/200580798-4ba3a6d3-33b9-4a19-bd8c-ca3f74d7823c.png)

## "Analyze Repins" ticked:
![image](https://user-images.githubusercontent.com/15476807/200581014-36b7abf3-1a61-4174-aac1-84fb5b27689c.png)

@fredeBio, please comment

**Comment by fredeBio** [comment]
I think we need to write REP singlets and REPINs when the REPIN option is ticked and otherwise we should not display the REPIN part. Is that possible? (just to make sure you have chosen the allREPs and allREPINs columns right?)

**Comment by CFGrote** [comment]
![image](https://user-images.githubusercontent.com/15476807/200861529-c26f7ec7-c1ec-4f36-9a3d-b1754aac6680.png)

![image](https://user-images.githubusercontent.com/15476807/200861599-8339714b-3f99-4c49-bb75-22486e80d795.png)

**Comment by fredeBio** [comment]
looks good!

**Comment by CFGrote** [comment]
Fixed by 194c6f6
