### ISSUE TITLE
MCL output

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#24]
It looks like MCL uses the error stream for outputting results. This is slightly annoying. Is there anything that we can do? I cannot think of something. Any thoughts?

**Comment by fredeBio** [comment]
I just found the line where MCL sets the log output to stderr. 
in util/err.c

   {  FILE* fp = mcxLogFILE ? mcxLogFILE : stderr  


Do you think we should just change it to stdout? Do we want to show the log output from mcl? I guess we could just not show it.

**Comment by CFGrote** [comment]
easier change would be to modify the mcl command line like
```
mcl <options> > /dev/null 2>&1, that would write all stdout to /dev/null (or whereever we want it to go) and redirect stderr to stdout

**Comment by CFGrote** [comment]
on the same token, what is `mcxLogFILE`, is it set by the user or hardcoded somewhere?

**Comment by CFGrote** [comment]
shell redirection does not work (seems not supported by the java system calling library). But I found out how to silence mcl output (option -V all). If we need to debug a run, can switch on logging by editing REPINProperties.java line 180.

**Comment by CFGrote** [comment]
Done by PR #36.
