### ISSUE TITLE
Plot message needs changing

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#25]
![Screenshot 2022-10-27 at 08 50 27](https://user-images.githubusercontent.com/17928432/198211647-065f5ed6-7586-425b-9967-c2ede5dd350e.png)
Instead of REP/RAYT group is empty, it should say: "No REPIN sequences could be identified in Group [x]" if identify REPINs was ticked.

If "identify REPINs" was not ticked it should say: "No REP sequences could be identified in Group [x]"

Do you think this is possible?

**Comment by CFGrote** [comment]
Fixed by 194c6f6

**Comment by CFGrote** [comment]
Done by #33 (and merged into master)
