### ISSUE TITLE
RAYTs are not linked/displayed in the Kingella test set: REPIN/RAYT distance parameter needs adding and changing to 200bp. 

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#27]
As far as I remember there is a RAYT that was identified and if we change the distance this RAYT is also linked to a group. There is at the moment no way to change the REPIN/RAYT distance on the website, but I think you planned to include this.

**Comment by CFGrote** [comment]
see #20, will be merged with #30
