### ISSUE TITLE
replace none with no 

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#29]
![Screenshot 2022-11-08 at 14 06 10](https://user-images.githubusercontent.com/17928432/200572481-ae7615f4-4aca-41df-bc9c-d155b0df0ebc.png)
We detected "no" REPINs/RAYTs instead of none

**Comment by CFGrote** [comment]
Actually, it's becoming increasingly cumbersome to maintain two reporting templates, one for email, one for web. Can we limit the
email report to saying "Your run is finished, please visit ... to see the results?

**Comment by fredeBio** [comment]
Yes, I think that would be fine.

**Comment by CFGrote** [comment]
done  4d6188b]
