### ISSUE TITLE
Add Smalt dataset

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#4]

**Comment by CFGrote** [comment]
@fredeBio do you have a run number for S.malt. ?

**Comment by fredeBio** [comment]
Yes, they are in the MS. 

[_1a8l7wu](http://rarefan.evolbio.mpg.de/results?run_id=_1a8l7wu)
[mknhxpv8](http://rarefan.evolbio.mpg.de/results?run_id=mknhxpv8)
[pgfmaxx5](http://rarefan.evolbio.mpg.de/results?run_id=pgfmaxx5)
[yy72i755](http://rarefan.evolbio.mpg.de/results?run_id=yy72i755)
[78eu9zl0](http://rarefan.evolbio.mpg.de/results?run_id=78eu9zl0)

**Comment by CFGrote** [comment]
I must have deleted them when I cleaned up old runs. I'm re-running them now and will save them in the old run directories so that all links remain valid.

**Comment by fredeBio** [comment]
I keep getting mailer demons. You might have put in a wrong email address.
----- Original Message -----

**Comment by CFGrote** [comment]
yes, wrong email (and multiple reruns ...)

**Comment by CFGrote** [comment]
New runs successfully finished and linked to old dataset URLs.
