### ISSUE TITLE
Cannot download data anymore

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#40]
http://rarefan.evolbio.mpg.de/results?run_id=6f4bnr8s

**Comment by fredeBio** [comment]
I think the problem is that if you leave the page open (in chrome at least) the page does not update after a certain point. And the link that is sent via email is sent before the job is done. 

So maybe the easiest fix would be to send the email only after the data is ready for download. And maybe have a not on the running site to manually refresh as long as the results are not present (once the results are ready the refresh note should disappear).

What do you think?

**Comment by CFGrote** [comment]
Fixed. The site just always refreshes after 60 seconds. The download link appears when the zip task is complete, in my test I saw it when following the link in the email. Can you confirm @fredeBio ?
