### ISSUE TITLE
REP singlets name needs to change

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#42]
Hey Carsten,
ich habe mich geirrt. "REP singlets" war doch falsch. Es sollte "REP/REPINs" sein. Kannst du das vielleicht nochmal ändern?

Danke und Sorry!
![Screenshot 2022-11-17 at 10 28 21](https://user-images.githubusercontent.com/17928432/202408302-b4b29f7c-bb53-4054-99f4-2ea03600ffe6.png)

**Comment by CFGrote** [comment]
ok, kein problem

**Comment by fredeBio** [comment]
For some reason this is not changed when I run rarefan:
![Screenshot 2022-12-01 at 14 37 42](https://user-images.githubusercontent.com/17928432/205066952-b071ed07-d756-4527-8819-c11668d28fe1.png)
Jetzt verstehe ich auch warum :). Ich meinte "REP singlets" das under "Group" steht.

**Comment by fredeBio** [comment]
Aber die Änderung, die du eingefügt hast kann auch so bleiben.

**Comment by fredeBio** [comment]
Also ich versuche es nochmal:
[issue.pdf](https://github.com/mpievolbio-scicomp/rarefan/files/10217577/issue.pdf)

**Comment by CFGrote** [comment]
Is this still active?
