### ISSUE TITLE
Check submitted data

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#46]
Run zo6ctgd4 (rerun of  gvnnqk79): Submitted data is a protein fasta. java starts but hangs on reporting "Wrong letter in DNA sequence".

Need to check if all submitted fenomes are NA sequences, not proteins or anything else and report proper error message to user if not.

**Comment by fredeBio** [comment]
I will look into it!

----- Original Message -----
From: "Carsten Fortmann-Grote" ***@***.***>
To: "mpievolbio-scicomp/rarefan" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, December 20, 2022 12:57:00 PM
Subject: [mpievolbio-scicomp/rarefan] Check submitted data (Issue #46)

Run zo6ctgd4 (rerun of  gvnnqk79): Submitted data is a protein fasta. java starts but hangs on reporting "Wrong letter in DNA sequence".

Need to check if all submitted fenomes are NA sequences, not proteins or anything else and report proper error message to user if not.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mpievolbio-scicomp/rarefan/issues/46

**Comment by fredeBio** [comment]
Hey Carsten,
I just submitted this job. So I guess the problem is not fixed yet: http://rarefan.evolbio.mpg.de/results?run_id=1q497hyd
Can you let me know when you update rarefan (and maybe also when you integrate the DNA sequence checking?). So I can tell our reviewers that we fixed the issue?

**Comment by CFGrote** [comment]
no it's not on the web server yet. i'm currently testing your changes
locally, if everything works i'll push it to the server.

**Comment by fredeBio** [comment]
Thanks!
----- Original Message -----

**Comment by CFGrote** [comment]
Done by merging #47

**Comment by fredeBio** [comment]
Vielen Dank Carsten! Ich schreibe ihnen jetzt eine email.

----- Original Message -----

**Comment by fredeBio** [comment]
Ach ja, wir sollten wahrscheinlich noch eine Funktion einbauen, die Jobs killed, die länger als 3h laufen.

----- Original Message -----
