### ISSUE TITLE
Report table if Analyse REPINs is off.

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#48]
The results table is messed up if analyse repins is switched off. the rows are misaligned, first counts appear in the header row. Example is run ajwtiy4s.

**Comment by fredeBio** [comment]
To me the table seems fine. There are just columns missing. The same for analysis with REPINs.

----- Original Message -----
From: "Carsten Fortmann-Grote" ***@***.***>
To: "mpievolbio-scicomp/rarefan" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Wednesday, January 11, 2023 11:18:48 AM
Subject: [mpievolbio-scicomp/rarefan] Report table if Analyse REPINs is off. (Issue #48)

The results table is messed up if analyse repins is switched off. the rows are misaligned, first counts appear in the header row. Example is run ajwtiy4s.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mpievolbio-scicomp/rarefan/issues/48

**Comment by CFGrote** [comment]
The group index is taken from the presAbs_*.txt filenames (presAbs_1.txt becomes Group 1 etc.). The files are sorted alphabetically, so presAbs_10.txt comes before presAbs_2.txt etc. Since we only report the first 12 groups (not sure where that is configured), many groups seem to be missing, but they are actually in the database. Guess this can be fixed by sorting filenames numerically, right? How many groups should we put into the table if there are many?

**Comment by fredeBio** [comment]
I see. Interesting. Yeah, I think we can fix it by doing a numerical sort. I think 9 groups would be good. Similar to the plot. Maybe we can also only plot the groups that contain data. So the first page corresponds to the plots.

----- Original Message -----

**Comment by CFGrote** [comment]
After the fix, rerunning ajwtiy4s yields proper sorting of groups.
