### ISSUE TITLE
Fix gff3 exporter

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#62]
Merge frederic's branch.

**Comment by CFGrote** [comment]
Hi @fredeBio , how can I test the fix works as intended?

**Comment by fredeBio** [comment]
Hey Carsten,
I just changed one value in the gff3 file. The start of the genome annotation is now always set to one.

Cheers,
Frederic

----- Original Message -----

**Comment by CFGrote** [comment]
ok, i pushed the changes to master branch and updated the server. Can you check it works as intended, @fredeBio, please?
