### ISSUE TITLE
The test data sets on the website are deleted.

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#63]
We need to restore the test datasets on the website.

**Comment by CFGrote** [comment]
the good news is that the data are not actually deleted, they are present in the directory.
one issue was that there was no space left on the harddisk of the server.

i'm on it.



Regards, Carsten

**Comment by CFGrote** [comment]
turned out the database server was not running as a side effect of full disk. restarting db and rarefan fixed it, all example datasets are now available, again.
