### ISSUE TITLE
Plotting the data does not work

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#8]
Here the plot site does not work:

http://rarefan.evolbio.mpg.de//shiny/analysis/?run_id=9j41ytet

**Comment by CFGrote** [comment]
there are only 6 colors defined in analysis.R. repin_rayt_association.txt lists all strains as beloning to REPINgroup 7, so this crashes when R tries to
acess colors[7].

**Comment by fredeBio** [comment]
Das hatten wir doch schon vor Ewigkeiten gelöst. Warum geht es denn nicht mehr?
----- Original Message -----

**Comment by CFGrote** [comment]
kann mich nicht erinnern, dass wir das geloest hatten. der vector colors =
c(...)  in analysis.R ist schon seit anfang an so definiert, irgendwann hatten wir mal eine sechste
farbe eingefuegt, aber dass >6 repingroups in einem datensatz sind, war bislang
nicht der fall und entsprechend tauchte der fehler nicht auf. hab jetzt 15
verschiedene farben aus kombination von zwei qualitativen farbskalen eingebaut,
solange nicht mehr repingrous rauskommen, sollte das ok sein. falls du eine
bessere idee hast, sag bescheid.

**Comment by fredeBio** [comment]
Hey Carsten,
ich glaube wir hatten einfach gesagt, dass wir alle REPIN groups ignorieren die über 6 hinausgehen. Ich glaube wir hatten auch instances wo das der Fall war. Aber kann mich auch nicht mehr erinnern. Aber der Datensatz den ich gerade analysiere macht ein paar Probleme. Ich glaube da kommen noch mehr bugs...

----- Original Message -----

**Comment by CFGrote** [comment]
ja das wuerde es natuerlich einfach machen. soll ich das so implementieren? oder warten bis deine neuen bugs identifiziert sind?

**Comment by fredeBio** [comment]
Ja, das können wir machen. Ich muss nochmal sehen was das mit den anderen bugs auf sich hat. Vielleicht muss ich einfach nur REALPHY ändern und der Rest kann so bleiben. Aber erstmal gucken.

----- Original Message -----

**Comment by CFGrote** [comment]
@fredeBio, any update? which repins should we support, 0-5 or 0-6?

**Comment by fredeBio** [comment]
No idea :( Well in the syringae dataset REPINs are found at group 7

----- Original Message -----

**Comment by CFGrote** [comment]
REPIN group index is limited to 8 now.
