### ISSUE TITLE
NZ_13V is not part of the genome tree

### ISSUE THREAD

**Issue by fredeBio** [mpievolbio-scicomp/rarefan#9]
see: http://rarefan.evolbio.mpg.de//shiny/analysis/?run_id=3slnqi62

**Comment by CFGrote** [comment]
the logs say 
```
Note: taxon 'NZ_13V_1' is a duplicate of taxon 'Shaanxi_M228_1'.
Note: taxon 'NZ_13V_0' is a duplicate of taxon 'Shaanxi_M228_0'.
```

I dimly recall that we had a similar case before but can't find it anymore. Maybe the label is just hidden behind "Shaanxi..." ?

**Comment by fredeBio** [comment]
Yes, it was a setting in PhyML. I think we might have just changed the phyml version at the time.

----- Original Message -----

**Comment by CFGrote** [comment]
that's right. but i have not changed phyml version ...
but it's a lead i'll track down.

**Comment by CFGrote** [comment]
I found the old issue over at gitlab (https://gitlab.gwdg.de/mpievolbio-scicomp/repinpop/-/issues/99). Phyml has not changed on the server.

**Comment by CFGrote** [comment]
Looked up the phyml documentation, it has a `--leave_duplicates` option. Maybe that solves the issue?

**Comment by fredeBio** [comment]
So we just change the phyml command? That would be a nice and easy fix.

----- Original Message -----

**Comment by CFGrote** [comment]
I reran phyml with `--leave_duplicates` on the server, @fredeBio can you check the output at http://rarefan.evolbio.mpg.de//shiny/analysis/?run_id=3slnqi62 ?

**Comment by fredeBio** [comment]
Nz13 is still missing :(

----- Original Message -----

**Comment by CFGrote** [comment]
ah i see, you mean the tree in the REPINs tab. that is computed by andi+clustDist, not phyml, correct?

**Comment by fredeBio** [comment]
True! So we have double trouble now :D so we need to fix phyml (did you manage to do this?) and andi! but I don't remember andi causing this issue ever.

----- Original Message -----

**Comment by CFGrote** [comment]
i need to test the phyml thing locally first. 

andi does not like DOS filetype, in particular the end-of-line encoding. NZ_13V.fas happens to be DOS encoded, the other files are all unix encoded. rewriting NZ_13V.fas to unix solves the issue.

**Comment by CFGrote** [comment]
fixed:

http://rarefan.evolbio.mpg.de//shiny/analysis/?run_id=3slnqi62

**Comment by fredeBio** [comment]
How the hell did this happen??? But I guess it will never happen again now?

----- Original Message -----

**Comment by fredeBio** [comment]
Looks good :)

----- Original Message -----

**Comment by CFGrote** [comment]
submitter must have opened the file in some windows app and then saved in dos format. we need to check somewhere that all files are unix encoded and/or convert to unix as needed.

**Comment by CFGrote** [comment]
PR #10 addresses this issue. All files are rewritten with explicit unix formatting.

**Comment by CFGrote** [comment]
now!

**Comment by CFGrote** [comment]
no wait, it's still missing ???
